### PR TITLE
Update 2022.json

### PR DESCRIPTION
**Pull request by jeffcaron**
Added Maplewood through White Bear Lake from https://thecatholicspirit.com/nomeat/

### CODE REVIEW

**Comment by jeffcaron** [comment]
New commit that will hopefully fix the issue.

**Comment by jeffcaron** [comment]
Ready. Maybe???
Full of confidence. Kinda.

**Comment by mftruso** [comment]
@jeffcaron please run `npm run lintfix`

**Comment by mftruso** [comment]
Resolved by https://github.com/saint-isidore-guild/church-dinner-finder/pull/39

**Pull request closed without merging**
